// File: subject.js
// Description: Provides all course subjects.

const Subject = Object.freeze([
  {code: "ALS", name: "Academic Learning Services"},
  {code: "ACTG", name: "Accounting"},
  {code: "AHE", name: "Adult Ed & Higher Ed Leadershp"},
  {code: "AAE", name: "Aeronautical & Astronaut. Eng."},
  {code: "AS", name: "Aerospace Studies"},
  {code: "AED", name: "Agricultural Education"},
  {code: "AGRI", name: "Agricultural Sci"},
  {code: "AG", name: "Agriculture-General"},
  {code: "ASL", name: "American Sign Language"},
  {code: "AMS", name: "American Studies Program"},
  {code: "ANS", name: "Animal Sciences"},
  {code: "ANTH", name: "Anthropology"},
  {code: "AEC", name: "Applied Economics"},
  {code: "AJ", name: "Applied Journalism"},
  {code: "ARAB", name: "Arabic"},
  {code: "ARE", name: "Architectural Engineering"},
  {code: "ART", name: "Art"},
  {code: "ASN", name: "Asian Languages and Culture"},
  {code: "ATS", name: "Atmospheric Sciences"},
  {code: "BB", name: "Biochemistry and Biophysics"},
  {code: "BHS", name: "BioHealth Sciences"},
  {code: "BEE", name: "Biological & Ecological Engr"},
  {code: "BDS", name: "Biological Data Sciences"},
  {code: "BIOE", name: "Biological Engineering"},
  {code: "BI", name: "Biology"},
  {code: "BRR", name: "Bioresource Research"},
  {code: "BOT", name: "Botany and Plant Pathology"},
  {code: "BA", name: "Business Administration"},
  {code: "CBEE", name: "Chem, Bio, Enviro Engineering"},
  {code: "CHE", name: "Chemical Engineering"},
  {code: "CH", name: "Chemistry"},
  {code: "CHN", name: "Chinese"},
  {code: "CCE", name: "Civil and Construction Engr"},
  {code: "CE", name: "Civil Engineering"},
  {code: "CSSA", name: "College Student Services Admin"},
  {code: "COMM", name: "Communication"},
  {code: "CS", name: "Computer Science"},
  {code: "CEM", name: "Construction Engineering Mngmt"},
  {code: "COUN", name: "Counseling"},
  {code: "CSS", name: "Crop & Soil Science"},
  {code: "CROP", name: "Crop Science"},
  {code: "DSGN", name: "Design"},
  {code: "DHE", name: "Design and Human Environment"},
  {code: "ECON", name: "Economics"},
  {code: "ED", name: "Education"},
  {code: "ECE", name: "Electrical & Computer Engineer"},
  {code: "ESE", name: "Energy Systems Engineering"},
  {code: "ENGR", name: "Engineering Science"},
  {code: "ENG", name: "English"},
  {code: "ENT", name: "Entomology"},
  {code: "EAH", name: "Environmental Arts & Humanities"},
  {code: "ENVE", name: "Environmental Engineering"},
  {code: "ENSC", name: "Environmental Sciences"},
  {code: "ES", name: "Ethnic Studies"},
  {code: "FILM", name: "Film Studies"},
  {code: "FIN", name: "Finance"},
  {code: "FW", name: "Fisheries and Wildlife"},
  {code: "FCSJ", name: "Food in Culture, Social Justice"},
  {code: "FST", name: "Food Science and Technology"},
  {code: "FES", name: "Forest Ecosystems and Society"},
  {code: "FE", name: "Forest Engineering"},
  {code: "FOR", name: "Forestry"},
  {code: "FR", name: "French"},
  {code: "GS", name: "General Science"},
  {code: "GEOG", name: "Geography"},
  {code: "GPH", name: "Geophysics"},
  {code: "GEO", name: "Geosciences"},
  {code: "GER", name: "German"},
  {code: "GRAD", name: "Graduate Education"},
  {code: "GD", name: "Graphic Design"},
  {code: "HHS", name: "Health and Human Sciences"},
  {code: "HEBR", name: "Hebrew"},
  {code: "HST", name: "History"},
  {code: "HSTS", name: "History of Science"},
  {code: "HC", name: "Honors College"},
  {code: "HORT", name: "Horticulture"},
  {code: "HM", name: "Hospitality Management"},
  {code: "HDFS", name: "Human Dev and Family Sciences"},
  {code: "HEST", name: "Humanitarian Engr Sci & Tech"},
  {code: "IE", name: "Industrial and Mfg Engineering"},
  {code: "IB", name: "Integrative Biology"},
  {code: "IEPA", name: "Intensive English Pgm Acad Eng"},
  {code: "IEPG", name: "Intensive English Pgm Gen Engl"},
  {code: "IEPH", name: "Intensive English Pgm Gen Engl"},
  {code: "IST", name: "Interdisciplinary Programs"},
  {code: "INTL", name: "International Degree"},
  {code: "IT", name: "Italian"},
  {code: "JPN", name: "Japanese"},
  {code: "KIN", name: "Kinesiology"},
  {code: "KOR", name: "Korean"},
  {code: "LEAD", name: "Leadership"},
  {code: "LA", name: "Liberal Arts"},
  {code: "LS", name: "Liberal Studies"},
  {code: "LIB", name: "Library & Information Science"},
  {code: "LING", name: "Linguistics"},
  {code: "MGMT", name: "Management"},
  {code: "MFGE", name: "Manufacturing Engineering"},
  {code: "MRM", name: "Marine Resource Management"},
  {code: "MRKT", name: "Marketing"},
  {code: "MNR", name: "Master of Natural Resources"},
  {code: "MPP", name: "Master of Public Policy"},
  {code: "MATS", name: "Materials Science"},
  {code: "MTH", name: "Mathematics"},
  {code: "MIME", name: "Mech/Ind/Mfg Engineering"},
  {code: "ME", name: "Mechanical Engineering"},
  {code: "MB", name: "Microbiology"},
  {code: "MS", name: "Military Science"},
  {code: "MCB", name: "Molecular & Cellular Biology"},
  {code: "MUS", name: "Music"},
  {code: "MUP", name: "Music (Studio)"},
  {code: "MUED", name: "Music Education"},
  {code: "NR", name: "Natural Resources"},
  {code: "NS", name: "Naval Science"},
  {code: "NMC", name: "New Media Communications"},
  {code: "NSE", name: "Nuclear Science & Engineering"},
  {code: "NUR", name: "Nursing"},
  {code: "NUTR", name: "Nutrition"},
  {code: "OEAS", name: "Ocean Earth & Atmospheric Sci"},
  {code: "OC", name: "Oceanography"},
  {code: "OP", name: "Outdoor Products"},
  {code: "PAX", name: "Peace Studies"},
  {code: "PHAR", name: "Pharmacy"},
  {code: "PHL", name: "Philosophy"},
  {code: "PAC", name: "Physical Activity Courses"},
  {code: "PT", name: "Physical Therapy/Therapist"},
  {code: "PH", name: "Physics"},
  {code: "PBG", name: "Plant Breeding & Genetics"},
  {code: "PS", name: "Political Science"},
  {code: "PSM", name: "Professional Science Masters"},
  {code: "PSY", name: "Psychology"},
  {code: "H", name: "Public Health"},
  {code: "PPOL", name: "Public Policy"},
  {code: "QS", name: "Queer Studies"},
  {code: "RNG", name: "Rangeland Ecology & Management"},
  {code: "REL", name: "Religious Studies"},
  {code: "ROB", name: "Robotics"},
  {code: "RS", name: "Rural Studies"},
  {code: "RUS", name: "Russian"},
  {code: "SED", name: "Science & Mathematics Educ"},
  {code: "SSCI", name: "Social Science"},
  {code: "SOC", name: "Sociology"},
  {code: "SE", name: "Software Engineering"},
  {code: "SOIL", name: "Soil Science"},
  {code: "SPAN", name: "Spanish"},
  {code: "ST", name: "Statistics"},
  {code: "SUS", name: "Sustainability"},
  {code: "SNR", name: "Sustainable Natural Resources"},
  {code: "TA", name: "Theatre Arts"},
  {code: "TRAL", name: "Tourism, Recreat, Adven. Lead."},
  {code: "TOX", name: "Toxicology"},
  {code: "TCS", name: "Twentieth Century Studies"},
  {code: "UEXP", name: "University Experience"},
  {code: "VMB", name: "Veterinary Medicine Biomedical"},
  {code: "VMC", name: "Veterinary Medicine Clinical"},
  {code: "WRE", name: "Water Resources Engineering"},
  {code: "WRP", name: "Water Resources Policy and Mgt"},
  {code: "WRS", name: "Water Resources Science"},
  {code: "WGSS", name: "Women, Gender, and Sexuality"},
  {code: "WSE", name: "Wood Science and Engineering"},
  {code: "WLC", name: "World Languages and Cultures"},
  {code: "WR", name: "Written English"},
  {code: "Z", name: "Zoology"}
]);
exports.Subject = Subject;
